### ISSUE TITLE
Proportion -> correlation: errors with unused arguments (assignment.method = "pearson", reorder = input$sampleOrder)

### ISSUE THREAD

**Issue by schmic05** [lutsik/FactorViz#36]
I don't know what these arguments should be used for, thus we should remove them from the function call.

**Comment by shashwatsahay** [comment]
Hey Michael,

It is realted to the "..." Being passed into feature.corr function in
MedeCom. I fixed it in the devel branch of MeDeCom two days back.


Regards
Shashwat Sahay

**Comment by schmic05** [comment]
You were right, it works with the current version of MeDeCom.
